### ISSUE TITLE
Please support crossOrigin Texture

### ISSUE THREAD

**Issue by cx20** [effekseer/EffekseerForWebGL#1]
I tried to display the sample of effekseer using the RawGit service.
https://cdn.rawgit.com/effekseer/EffekseerForWebGL/7a1b035c/Release/Sample/index.html
However, texture could not be loaded due to crossOrigin error.
```
effekseer.min.js:50 Uncaught DOMException: Failed to execute 'texImage2D' on 'WebGLRenderingContext': The cross-origin image at https://raw.githubusercontent.com/effekseer/EffekseerForWebGL/7a1b035c/Release/Sample/Resource/Texture/Burst01.png may not be loaded.
    at Array.<anonymous> (https://cdn.rawgit.com/effekseer/EffekseerForWebGL/7a1b035c/Release/effekseer.min.js:50:128)
    at _emscripten_asm_const_iii (https://cdn.rawgit.com/effekseer/EffekseerForWebGL/7a1b035c/Release/effekseer.min.js:51:149)
    at Array.ZC (https://cdn.rawgit.com/effekseer/EffekseerForWebGL/7a1b035c/Release/effekseer.min.js:1716:147)
    at Array.Wh (https://cdn.rawgit.com/effekseer/EffekseerForWebGL/7a1b035c/Release/effekseer.min.js:795:125)
    at Object.vC [as ReloadResources] (https://cdn.rawgit.com/effekseer/EffekseerForWebGL/7a1b035c/Release/effekseer.min.js:1708:412)
    at EffekseerEffect._reload (https://cdn.rawgit.com/effekseer/EffekseerForWebGL/7a1b035c/Release/effekseer.min.js:1942:344)
    at EffekseerEffect._update (https://cdn.rawgit.com/effekseer/EffekseerForWebGL/7a1b035c/Release/effekseer.min.js:1943:28)
    at https://cdn.rawgit.com/effekseer/EffekseerForWebGL/7a1b035c/Release/effekseer.min.js:1947:213
    at HTMLImageElement.image.onload (https://cdn.rawgit.com/effekseer/EffekseerForWebGL/7a1b035c/Release/effekseer.min.js:1945:442)
```
Since crossOrigin is enabled on hosting server of github, texture can be loaded if you activate crossOrigin on JS side.

See: http://runstant.com/phi/projects/4281bc77
```js
  var img = new Image();
  img.crossOrigin = 'anonymous';
  img.src = url;
```

**Comment by ueshita** [comment]
I fixed this issue.
Thank you for your advice!

**Comment by cx20** [comment]
I confirmed that the sample works.
https://cdn.rawgit.com/effekseer/EffekseerForWebGL/42f8bc69/Release/Sample/index.html

![image](https://cloud.githubusercontent.com/assets/1833979/26555185/e08d9bcc-44ce-11e7-9b3a-1d2d36cd19fb.png)
